//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeitorPassagensPendentesBatch.CommandQuery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LeitorPassagensPendentesBatchResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeitorPassagensPendentesBatchResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeitorPassagensPendentesBatch.CommandQuery.Resources.LeitorPassagensPendentesBatc" +
                            "hResource", typeof(LeitorPassagensPendentesBatchResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Construção do leitor de passagens pendentes..
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Enviando mensagens da concessionária {0} para processamento..
        /// </summary>
        public static string EnviarMensagensParaProcessamento {
            get {
                return ResourceManager.GetString("EnviarMensagensParaProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Erro: {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Erro ao tentar enviar as mensagens para a API do akka. {0}.
        /// </summary>
        public static string ErrorRest {
            get {
                return ResourceManager.GetString("ErrorRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Fila {0} não foi encontrada no barramento do azure..
        /// </summary>
        public static string FilaNaoExiste {
            get {
                return ResourceManager.GetString("FilaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Fim do envio de {0} mensagens da concessionária {1} para API de processamento..
        /// </summary>
        public static string FimEnvioParaApiPRocessamento {
            get {
                return ResourceManager.GetString("FimEnvioParaApiPRocessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Final da leitura de passagens pendentes..
        /// </summary>
        public static string FinalProcesso {
            get {
                return ResourceManager.GetString("FinalProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Obtendo conexões com as bases de dados..
        /// </summary>
        public static string GetDataSource {
            get {
                return ResourceManager.GetString("GetDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Inicio do envio de {0} mensagens da concessionária {1} para API de processamento..
        /// </summary>
        public static string InicioEnvioParaApiPRocessamento {
            get {
                return ResourceManager.GetString("InicioEnvioParaApiPRocessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Inicio da leitura de passagens pendentes..
        /// </summary>
        public static string InicioProcesso {
            get {
                return ResourceManager.GetString("InicioProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Obtendo as concessionárias para processamento..
        /// </summary>
        public static string ObterConcessionariasParaProcessamento {
            get {
                return ResourceManager.GetString("ObterConcessionariasParaProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Obtendo as passagens pendentes de processamento no tópico {0}. {1} Execução..
        /// </summary>
        public static string ObterPassagensPendentesBarramento {
            get {
                return ResourceManager.GetString("ObterPassagensPendentesBarramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Encontrado {0} concessionárias ativas no protocolo Artesp..
        /// </summary>
        public static string QtdConcessionariasAtivasProtocolo {
            get {
                return ResourceManager.GetString("QtdConcessionariasAtivasProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Foram obtidas {0} mensagens na fila {1}..
        /// </summary>
        public static string QtdPassagensPendentesBarramento {
            get {
                return ResourceManager.GetString("QtdPassagensPendentesBarramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Nenhuma mensagem na fila da concessionaria {0}..
        /// </summary>
        public static string SemMensagensNaFila {
            get {
                return ResourceManager.GetString("SemMensagensNaFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensPendentesBatch - Total de {0}  foram enviadas para serem processadas no akka..
        /// </summary>
        public static string SucessoEnvio {
            get {
                return ResourceManager.GetString("SucessoEnvio", resourceCulture);
            }
        }
    }
}
