//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessadorPassagensActors.CommandQuery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransacaoAutorizacaoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransacaoAutorizacaoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("ProcessadorPassagensActors.CommandQuery.Resources.TransacaoAutorizacaoResource", typeof(TransacaoAutorizacaoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concessionaria inativa para o protocolo artesp, passagem: {0}.
        /// </summary>
        public static string ConcessionariaValidator {
            get {
                return ResourceManager.GetString("ConcessionariaValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) sem NumeroReenvio que possui &apos;MotivoReenvio&apos;..
        /// </summary>
        public static string EnvioPassagemValidatorComMotivoReenvio {
            get {
                return ResourceManager.GetString("EnvioPassagemValidatorComMotivoReenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na rotina: ({0}) - Chave: {0}   Exceção: {1}..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag de passagem ({0}) automática não informada..
        /// </summary>
        public static string FlagPassagemAutomaticaValidator {
            get {
                return ResourceManager.GetString("FlagPassagemAutomaticaValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) com horário não informado ou horário muito antigo ou horário no futuro.
        /// </summary>
        public static string HorarioPassagemValidator {
            get {
                return ResourceManager.GetString("HorarioPassagemValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) com valor zero que não possui &apos;MotivoSemValor&apos;..
        /// </summary>
        public static string MotivoSemValorValidator {
            get {
                return ResourceManager.GetString("MotivoSemValorValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) recebida com OSA ({1}) ID diferente do configurado para conectcar: {0}.
        /// </summary>
        public static string OsaIDValidatorNotEqual {
            get {
                return ResourceManager.GetString("OsaIDValidatorNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar Transacao: (PassagemException) - Chave: {0}  Motivo: {1}  Exceção: {2}..
        /// </summary>
        public static string PassagemException {
            get {
                return ResourceManager.GetString("PassagemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) manual que não possui &apos;MotivoManual&apos;..
        /// </summary>
        public static string PassagemManualMotivo {
            get {
                return ResourceManager.GetString("PassagemManualMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) manual sem valor bloqueado com motivo diferente de bloqueado..
        /// </summary>
        public static string PassagemManualMotivoBloqueado {
            get {
                return ResourceManager.GetString("PassagemManualMotivoBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem({0} fora do tempo limite de reenvio..
        /// </summary>
        public static string ReenvioPassagemValidatorForaLimite {
            get {
                return ResourceManager.GetString("ReenvioPassagemValidatorForaLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) fora da sequencia..
        /// </summary>
        public static string ReenvioPassagemValidatorForaSequencia {
            get {
                return ResourceManager.GetString("ReenvioPassagemValidatorForaSequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagem ({0}) com NumeroReenvio que não possui &apos;MotivoReenvio&apos;..
        /// </summary>
        public static string ReenvioPassagemValidatorSemMotivoReenvio {
            get {
                return ResourceManager.GetString("ReenvioPassagemValidatorSemMotivoReenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar Transacao: (TransacaoException) - Chave: {0}  Motivo: {1}  Exceção: {2}..
        /// </summary>
        public static string TransacaoException {
            get {
                return ResourceManager.GetString("TransacaoException", resourceCulture);
            }
        }
    }
}
