//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorPassagensPendentesBatch.CommandQuery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeradorPassagemPendenteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeradorPassagemPendenteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeradorPassagensPendentesBatch.CommandQuery.Resources.GeradorPassagemPendenteReso" +
                            "urce", typeof(GeradorPassagemPendenteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Construção do gerador de passagens pendentes..
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Processando passagens da concessionaria {0}.
        /// </summary>
        public static string Concessionaria {
            get {
                return ResourceManager.GetString("Concessionaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Configuração de sistema &apos;{0}&apos; inválida. Valor: &apos;{1}&apos;..
        /// </summary>
        public static string ConfiguracaoSistemaInvalida {
            get {
                return ResourceManager.GetString("ConfiguracaoSistemaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Enviando total de {0} passagens pendentes para a fila {1}..
        /// </summary>
        public static string EnviandoPassagem {
            get {
                return ResourceManager.GetString("EnviandoPassagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Erro: {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Falha na atualização do TTL das passagens pendentes enviadas..
        /// </summary>
        public static string FalhaAtualizacaoTTLPassagensPendentes {
            get {
                return ResourceManager.GetString("FalhaAtualizacaoTTLPassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Final da geração de passagens pendentes Artesp..
        /// </summary>
        public static string FinalProcesso {
            get {
                return ResourceManager.GetString("FinalProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Obtendo conexões com as bases de dados..
        /// </summary>
        public static string GetDataSource {
            get {
                return ResourceManager.GetString("GetDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Iniciando a atualização do TTL das passagens pendentes enviadas..
        /// </summary>
        public static string InicioAtualizacaoTTLPassagensPendentes {
            get {
                return ResourceManager.GetString("InicioAtualizacaoTTLPassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Início da geração de passagens pendentes Artesp..
        /// </summary>
        public static string InicioProcesso {
            get {
                return ResourceManager.GetString("InicioProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Não existe concessionárias configuradas..
        /// </summary>
        public static string NaoExisteConcessionarias {
            get {
                return ResourceManager.GetString("NaoExisteConcessionarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Não existe concessionárias configuradas para Artesp..
        /// </summary>
        public static string NaoExisteConcessionariasArtesp {
            get {
                return ResourceManager.GetString("NaoExisteConcessionariasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Não há configuração de sistema para a chave &apos;{0}&apos;..
        /// </summary>
        public static string NaoExisteConfiguracaoSistema {
            get {
                return ResourceManager.GetString("NaoExisteConfiguracaoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Não há passagens pendentes para processamento..
        /// </summary>
        public static string NaoExistePassagensPendentes {
            get {
                return ResourceManager.GetString("NaoExistePassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Obtendo configuração de sistema para a chave &apos;{0}&apos;..
        /// </summary>
        public static string ObterConfiguracaoSistema {
            get {
                return ResourceManager.GetString("ObterConfiguracaoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Obtendo passagens pendentes de processamento..
        /// </summary>
        public static string ObterPassagensPendentes {
            get {
                return ResourceManager.GetString("ObterPassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Passagens pendentes não enviadas ao barramento..
        /// </summary>
        public static string PassagensPendentesBarramentoNaoEnviadas {
            get {
                return ResourceManager.GetString("PassagensPendentesBarramentoNaoEnviadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Buscando tempo SLA das passagens..
        /// </summary>
        public static string PreencherSLAPassagensPendentes {
            get {
                return ResourceManager.GetString("PreencherSLAPassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Sucesso na atualização do TTL das passagens pendentes enviadas..
        /// </summary>
        public static string SucessoAtualizacaoTTLPassagensPendentes {
            get {
                return ResourceManager.GetString("SucessoAtualizacaoTTLPassagensPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeradorPassagensPendentesBatch - Fila {0} recebeu com sucesso o total de {1} passagens pendentes.
        /// </summary>
        public static string SucessoEnvio {
            get {
                return ResourceManager.GetString("SucessoEnvio", resourceCulture);
            }
        }
    }
}
