//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeitorPassagensProcessadasBatch.CommandQuery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LeitorPassagensProcessadasBatchResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeitorPassagensProcessadasBatchResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeitorPassagensProcessadasBatch.CommandQuery.Resources.LeitorPassagensProcessadas" +
                            "BatchResource", typeof(LeitorPassagensProcessadasBatchResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Erro: {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Erro ao tentar enviar as mensagens para a API de persistência
        ///. {0}.
        /// </summary>
        public static string ErrorRest {
            get {
                return ResourceManager.GetString("ErrorRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fila {0} não foi encontrada no barramento do azure..
        /// </summary>
        public static string FilaNaoExiste {
            get {
                return ResourceManager.GetString("FilaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens aprovadas Artesp para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensAprovadasArtesp {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensAprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens aprovadas EDI para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensAprovadasEDI {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensAprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens inválidas Artesp para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensInvalidasArtesp {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensInvalidasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens inválidas EDI para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensInvalidasEDI {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensInvalidasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens reprovadas Artesp para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensReprovadasArtesp {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensReprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do envio de {0} mensagens reprovadas EDI para a API de persistência.
        /// </summary>
        public static string FimEnvioApiPassagensReprovadasEDI {
            get {
                return ResourceManager.GetString("FimEnvioApiPassagensReprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens aprovadas Artesp..
        /// </summary>
        public static string FimLeituraPassagensAprovadasArtesp {
            get {
                return ResourceManager.GetString("FimLeituraPassagensAprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens aprovadas EDI..
        /// </summary>
        public static string FimLeituraPassagensAprovadasEDI {
            get {
                return ResourceManager.GetString("FimLeituraPassagensAprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens inválidas Artesp..
        /// </summary>
        public static string FimLeituraPassagensInvalidasArtesp {
            get {
                return ResourceManager.GetString("FimLeituraPassagensInvalidasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens inválidas EDI..
        /// </summary>
        public static string FimLeituraPassagensInvalidasEDI {
            get {
                return ResourceManager.GetString("FimLeituraPassagensInvalidasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens reprovadas Artesp..
        /// </summary>
        public static string FimLeituraPassagensReprovadasArtesp {
            get {
                return ResourceManager.GetString("FimLeituraPassagensReprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Fim do processo de leitura de passagens reprovadas EDI..
        /// </summary>
        public static string FimLeituraPassagensReprovadasEDI {
            get {
                return ResourceManager.GetString("FimLeituraPassagensReprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Final do processo de leitura de passagens processadas..
        /// </summary>
        public static string FinalProcesso {
            get {
                return ResourceManager.GetString("FinalProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens aprovadas Artesp para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensAprovadasArtesp {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensAprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens aprovadas EDI para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensAprovadasEDI {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensAprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens inválidas Artesp para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensInvalidasArtesp {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensInvalidasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens inválidas EDI para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensInvalidasEDI {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensInvalidasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens reprovadas Artesp para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensReprovadasArtesp {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensReprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do envio de {0} mensagens reprovadas EDI para a API..
        /// </summary>
        public static string InicioEnvioApiPassagensReprovadasEDI {
            get {
                return ResourceManager.GetString("InicioEnvioApiPassagensReprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens aprovadas Artesp..
        /// </summary>
        public static string InicioLeituraPassagensAprovadasArtesp {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensAprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens aprovadas EDI..
        /// </summary>
        public static string InicioLeituraPassagensAprovadasEDI {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensAprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens inválidas Artesp..
        /// </summary>
        public static string InicioLeituraPassagensInvalidasArtesp {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensInvalidasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens inválidas EDI..
        /// </summary>
        public static string InicioLeituraPassagensInvalidasEDI {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensInvalidasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens reprovadas Artesp..
        /// </summary>
        public static string InicioLeituraPassagensReprovadasArtesp {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensReprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens reprovadas EDI..
        /// </summary>
        public static string InicioLeituraPassagensReprovadasEDI {
            get {
                return ResourceManager.GetString("InicioLeituraPassagensReprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Inicio do processo de leitura de passagens processadas..
        /// </summary>
        public static string InicioProcesso {
            get {
                return ResourceManager.GetString("InicioProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens aprovadas Artesp..
        /// </summary>
        public static string QtdPassagensAprovadasArtesp {
            get {
                return ResourceManager.GetString("QtdPassagensAprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens aprovadas EDI..
        /// </summary>
        public static string QtdPassagensAprovadasEDI {
            get {
                return ResourceManager.GetString("QtdPassagensAprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens inválidas Artesp..
        /// </summary>
        public static string QtdPassagensInvalidasArtesp {
            get {
                return ResourceManager.GetString("QtdPassagensInvalidasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens inválidas EDI..
        /// </summary>
        public static string QtdPassagensInvalidasEDI {
            get {
                return ResourceManager.GetString("QtdPassagensInvalidasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens reprovadas Artesp..
        /// </summary>
        public static string QtdPassagensReprovadasArtesp {
            get {
                return ResourceManager.GetString("QtdPassagensReprovadasArtesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Foram encontradas {0} mensagens reprovadas EDI..
        /// </summary>
        public static string QtdPassagensReprovadasEDI {
            get {
                return ResourceManager.GetString("QtdPassagensReprovadasEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Total de {0} mensagens foram enviadas para serem processadas na API de persistência.
        /// </summary>
        public static string SucessoEnvio {
            get {
                return ResourceManager.GetString("SucessoEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeitorPassagensProcessadasBatch - Total de {0} mensagens foram enviadas para serem processadas na API de persistência.
        /// </summary>
        public static string SucessoEnvioInvalida {
            get {
                return ResourceManager.GetString("SucessoEnvioInvalida", resourceCulture);
            }
        }
    }
}
